
package com.ean.wsapi.hotel.v3;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-02-01T18:14:16.403Z
 * Generated source version: 2.7.2
 * 
 */
public final class HotelServices_HotelServicesImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://v3.hotel.wsapi.ean.com/", "HotelServicesImplService");

    private HotelServices_HotelServicesImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HotelServicesImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HotelServicesImplService ss = new HotelServicesImplService(wsdlURL, SERVICE_NAME);
        HotelServices port = ss.getHotelServicesImplPort();  
        
        {
        System.out.println("Invoking getList...");
        com.ean.wsapi.hotel.v3.HotelListRequest _getList_hotelListRequest = new com.ean.wsapi.hotel.v3.HotelListRequest();
        _getList_hotelListRequest.setApiKey("ApiKey-1932325626");
        _getList_hotelListRequest.setCid(1392594350792589805l);
        _getList_hotelListRequest.setCustomerIpAddress("CustomerIpAddress-1314996411");
        _getList_hotelListRequest.setCustomerSessionId("CustomerSessionId487131918");
        _getList_hotelListRequest.setCustomerUserAgent("CustomerUserAgent2144406936");
        com.ean.wsapi.hotel.v3.LocaleType _getList_hotelListRequestLocale = com.ean.wsapi.hotel.v3.LocaleType.TR_TR;
        _getList_hotelListRequest.setLocale(_getList_hotelListRequestLocale);
        _getList_hotelListRequest.setCurrencyCode("CurrencyCode1233790504");
        java.util.List<com.ean.wsapi.hotel.v3.MapEntry> _getList_hotelListRequestAdditionalData = new java.util.ArrayList<com.ean.wsapi.hotel.v3.MapEntry>();
        com.ean.wsapi.hotel.v3.MapEntry _getList_hotelListRequestAdditionalDataVal1 = new com.ean.wsapi.hotel.v3.MapEntry();
        _getList_hotelListRequestAdditionalDataVal1.setKey("Key-1982091113");
        _getList_hotelListRequestAdditionalDataVal1.setValue("Value432873259");
        _getList_hotelListRequestAdditionalData.add(_getList_hotelListRequestAdditionalDataVal1);
        _getList_hotelListRequest.getAdditionalData().addAll(_getList_hotelListRequestAdditionalData);
        _getList_hotelListRequest.setSig("Sig1347421308");
        _getList_hotelListRequest.setDebug(Boolean.valueOf(false));
        _getList_hotelListRequest.setTest(Boolean.valueOf(false));
        _getList_hotelListRequest.setMinorRev(Integer.valueOf(-1244746228));
        _getList_hotelListRequest.setAddress("Address-1068285614");
        _getList_hotelListRequest.setCity("City-1903144389");
        _getList_hotelListRequest.setStateProvinceCode("StateProvinceCode-1860359674");
        _getList_hotelListRequest.setPostalCode("PostalCode1858263024");
        _getList_hotelListRequest.setCountryCode("CountryCode1551465350");
        _getList_hotelListRequest.setDestinationId("DestinationId1313545583");
        _getList_hotelListRequest.setDestinationString("DestinationString1440739332");
        java.util.List<java.lang.Long> _getList_hotelListRequestHotelIdList = new java.util.ArrayList<java.lang.Long>();
        java.lang.Long _getList_hotelListRequestHotelIdListVal1 = Long.valueOf(1022912827096379870l);
        _getList_hotelListRequestHotelIdList.add(_getList_hotelListRequestHotelIdListVal1);
        _getList_hotelListRequest.getHotelIdList().addAll(_getList_hotelListRequestHotelIdList);
        _getList_hotelListRequest.setLatitude(Float.valueOf(0.821721f));
        _getList_hotelListRequest.setLongitude(Float.valueOf(0.35747987f));
        _getList_hotelListRequest.setSearchRadius(Integer.valueOf(-1306817330));
        com.ean.wsapi.hotel.v3.SearchRadiusUnitType _getList_hotelListRequestSearchRadiusUnit = com.ean.wsapi.hotel.v3.SearchRadiusUnitType.MI;
        _getList_hotelListRequest.setSearchRadiusUnit(_getList_hotelListRequestSearchRadiusUnit);
        com.ean.wsapi.hotel.v3.SortType _getList_hotelListRequestSort = com.ean.wsapi.hotel.v3.SortType.PRICE_AVERAGE;
        _getList_hotelListRequest.setSort(_getList_hotelListRequestSort);
        _getList_hotelListRequest.setPropertyName("PropertyName1852034117");
        java.util.List<java.lang.Integer> _getList_hotelListRequestAmenities = new java.util.ArrayList<java.lang.Integer>();
        java.lang.Integer _getList_hotelListRequestAmenitiesVal1 = Integer.valueOf(-1700461936);
        _getList_hotelListRequestAmenities.add(_getList_hotelListRequestAmenitiesVal1);
        _getList_hotelListRequest.getAmenities().addAll(_getList_hotelListRequestAmenities);
        _getList_hotelListRequest.setMinStarRating(Float.valueOf(0.5176775f));
        _getList_hotelListRequest.setMaxStarRating(Float.valueOf(0.32214934f));
        _getList_hotelListRequest.setMinTripAdvisorRating(Float.valueOf(0.5402667f));
        _getList_hotelListRequest.setMaxTripAdvisorRating(Float.valueOf(0.12913513f));
        _getList_hotelListRequest.setMinRate(Integer.valueOf(217273792));
        _getList_hotelListRequest.setMaxRate(Integer.valueOf(1240854560));
        java.util.List<java.lang.String> _getList_hotelListRequestPropertyCategory = new java.util.ArrayList<java.lang.String>();
        java.lang.String _getList_hotelListRequestPropertyCategoryVal1 = "_getList_hotelListRequestPropertyCategoryVal156858385";
        _getList_hotelListRequestPropertyCategory.add(_getList_hotelListRequestPropertyCategoryVal1);
        _getList_hotelListRequest.getPropertyCategory().addAll(_getList_hotelListRequestPropertyCategory);
        _getList_hotelListRequest.setSupplierType("SupplierType-582106423");
        _getList_hotelListRequest.setNumberOfBedRooms(Integer.valueOf(-416041389));
        _getList_hotelListRequest.setNumberOfResults(Integer.valueOf(580967855));
        _getList_hotelListRequest.setMaxRatePlanCount(Integer.valueOf(897835686));
        _getList_hotelListRequest.setArrivalDate("ArrivalDate-2020569634");
        _getList_hotelListRequest.setDepartureDate("DepartureDate1645530820");
        com.ean.wsapi.hotel.v3.RoomGroup _getList_hotelListRequestRoomGroup = new com.ean.wsapi.hotel.v3.RoomGroup();
        java.util.List<com.ean.wsapi.hotel.v3.Room> _getList_hotelListRequestRoomGroupRoom = new java.util.ArrayList<com.ean.wsapi.hotel.v3.Room>();
        com.ean.wsapi.hotel.v3.Room _getList_hotelListRequestRoomGroupRoomVal1 = new com.ean.wsapi.hotel.v3.Room();
        _getList_hotelListRequestRoomGroupRoomVal1.setNumberOfAdults(-885684282);
        _getList_hotelListRequestRoomGroupRoomVal1.setNumberOfChildren(Integer.valueOf(-2070171025));
        java.util.List<java.lang.Integer> _getList_hotelListRequestRoomGroupRoomVal1ChildAges = new java.util.ArrayList<java.lang.Integer>();
        _getList_hotelListRequestRoomGroupRoomVal1.getChildAges().addAll(_getList_hotelListRequestRoomGroupRoomVal1ChildAges);
        _getList_hotelListRequestRoomGroupRoomVal1.setFirstName("FirstName-98867176");
        _getList_hotelListRequestRoomGroupRoomVal1.setLastName("LastName795312406");
        _getList_hotelListRequestRoomGroupRoomVal1.setBedTypeId("BedTypeId1270682238");
        _getList_hotelListRequestRoomGroupRoomVal1.setBedTypeDescription("BedTypeDescription956253318");
        _getList_hotelListRequestRoomGroupRoomVal1.setNumberOfBeds(Integer.valueOf(493269493));
        com.ean.wsapi.hotel.v3.SmokingPreference _getList_hotelListRequestRoomGroupRoomVal1SmokingPreference = com.ean.wsapi.hotel.v3.SmokingPreference.E;
        _getList_hotelListRequestRoomGroupRoomVal1.setSmokingPreference(_getList_hotelListRequestRoomGroupRoomVal1SmokingPreference);
        _getList_hotelListRequestRoomGroupRoomVal1.setRoomTypeCode("RoomTypeCode-1778944043");
        _getList_hotelListRequestRoomGroupRoomVal1.setRateCode("RateCode490038894");
        _getList_hotelListRequestRoomGroupRoomVal1.setRateKey("RateKey1874547157");
        _getList_hotelListRequestRoomGroupRoomVal1.setRoomDescription("RoomDescription859229993");
        _getList_hotelListRequestRoomGroupRoomVal1.setChargeableRate(Float.valueOf(0.19382453f));
        _getList_hotelListRequestRoomGroupRoom.add(_getList_hotelListRequestRoomGroupRoomVal1);
        _getList_hotelListRequestRoomGroup.getRoom().addAll(_getList_hotelListRequestRoomGroupRoom);
        _getList_hotelListRequest.setRoomGroup(_getList_hotelListRequestRoomGroup);
        java.util.List<com.ean.wsapi.hotel.v3.RatePlanType> _getList_hotelListRequestRateType = new java.util.ArrayList<com.ean.wsapi.hotel.v3.RatePlanType>();
        com.ean.wsapi.hotel.v3.RatePlanType _getList_hotelListRequestRateTypeVal1 = com.ean.wsapi.hotel.v3.RatePlanType.MERCHANT_CORPORATE;
        _getList_hotelListRequestRateType.add(_getList_hotelListRequestRateTypeVal1);
        _getList_hotelListRequest.getRateType().addAll(_getList_hotelListRequestRateType);
        _getList_hotelListRequest.setCacheLocation("CacheLocation700016368");
        _getList_hotelListRequest.setCacheKey("CacheKey2019349466");
        java.util.List<com.ean.wsapi.hotel.v3.HotelListOption> _getList_hotelListRequestOptions = new java.util.ArrayList<com.ean.wsapi.hotel.v3.HotelListOption>();
        com.ean.wsapi.hotel.v3.HotelListOption _getList_hotelListRequestOptionsVal1 = com.ean.wsapi.hotel.v3.HotelListOption.ROOM_RATE_DETAILS;
        _getList_hotelListRequestOptions.add(_getList_hotelListRequestOptionsVal1);
        _getList_hotelListRequest.getOptions().addAll(_getList_hotelListRequestOptions);
        com.ean.wsapi.hotel.v3.MultiRoomAvailType _getList_hotelListRequestMultiRoomAvail = com.ean.wsapi.hotel.v3.MultiRoomAvailType.BASIC;
        _getList_hotelListRequest.setMultiRoomAvail(_getList_hotelListRequestMultiRoomAvail);
        _getList_hotelListRequest.setMerchantScoringSource("MerchantScoringSource-710756471");
        _getList_hotelListRequest.setScoringAlgorithmId(Integer.valueOf(1241272915));
        _getList_hotelListRequest.setIgnoreMmOverrides(Boolean.valueOf(true));
        com.ean.wsapi.hotel.v3.SupplierCacheTolerance _getList_hotelListRequestSupplierCacheTolerance = com.ean.wsapi.hotel.v3.SupplierCacheTolerance.MED;
        _getList_hotelListRequest.setSupplierCacheTolerance(_getList_hotelListRequestSupplierCacheTolerance);
        _getList_hotelListRequest.setDatelessSupplierSort(Boolean.valueOf(false));
        _getList_hotelListRequest.setIncludeDetails(Boolean.valueOf(true));
        com.ean.wsapi.hotel.v3.HotelListResponse _getList__return = port.getList(_getList_hotelListRequest);
        System.out.println("getList.result=" + _getList__return);


        }
        {
        System.out.println("Invoking getAvailability...");
        com.ean.wsapi.hotel.v3.HotelRoomAvailabilityRequest _getAvailability_hotelRoomAvailabilityRequest = new com.ean.wsapi.hotel.v3.HotelRoomAvailabilityRequest();
        _getAvailability_hotelRoomAvailabilityRequest.setApiKey("ApiKey1121783372");
        _getAvailability_hotelRoomAvailabilityRequest.setCid(4359131026297322356l);
        _getAvailability_hotelRoomAvailabilityRequest.setCustomerIpAddress("CustomerIpAddress-900357378");
        _getAvailability_hotelRoomAvailabilityRequest.setCustomerSessionId("CustomerSessionId-729725875");
        _getAvailability_hotelRoomAvailabilityRequest.setCustomerUserAgent("CustomerUserAgent-1270125291");
        com.ean.wsapi.hotel.v3.LocaleType _getAvailability_hotelRoomAvailabilityRequestLocale = com.ean.wsapi.hotel.v3.LocaleType.UK_UA;
        _getAvailability_hotelRoomAvailabilityRequest.setLocale(_getAvailability_hotelRoomAvailabilityRequestLocale);
        _getAvailability_hotelRoomAvailabilityRequest.setCurrencyCode("CurrencyCode-194078446");
        java.util.List<com.ean.wsapi.hotel.v3.MapEntry> _getAvailability_hotelRoomAvailabilityRequestAdditionalData = new java.util.ArrayList<com.ean.wsapi.hotel.v3.MapEntry>();
        com.ean.wsapi.hotel.v3.MapEntry _getAvailability_hotelRoomAvailabilityRequestAdditionalDataVal1 = new com.ean.wsapi.hotel.v3.MapEntry();
        _getAvailability_hotelRoomAvailabilityRequestAdditionalDataVal1.setKey("Key2025640499");
        _getAvailability_hotelRoomAvailabilityRequestAdditionalDataVal1.setValue("Value932595048");
        _getAvailability_hotelRoomAvailabilityRequestAdditionalData.add(_getAvailability_hotelRoomAvailabilityRequestAdditionalDataVal1);
        _getAvailability_hotelRoomAvailabilityRequest.getAdditionalData().addAll(_getAvailability_hotelRoomAvailabilityRequestAdditionalData);
        _getAvailability_hotelRoomAvailabilityRequest.setSig("Sig-1806185208");
        _getAvailability_hotelRoomAvailabilityRequest.setDebug(Boolean.valueOf(true));
        _getAvailability_hotelRoomAvailabilityRequest.setTest(Boolean.valueOf(true));
        _getAvailability_hotelRoomAvailabilityRequest.setMinorRev(Integer.valueOf(2141306200));
        _getAvailability_hotelRoomAvailabilityRequest.setHotelId(-6469650339504358760l);
        _getAvailability_hotelRoomAvailabilityRequest.setArrivalDate("ArrivalDate685897345");
        _getAvailability_hotelRoomAvailabilityRequest.setDepartureDate("DepartureDate-572763078");
        _getAvailability_hotelRoomAvailabilityRequest.setNumberOfBedRooms(Integer.valueOf(1902779243));
        com.ean.wsapi.hotel.v3.SupplierType _getAvailability_hotelRoomAvailabilityRequestSupplierType = com.ean.wsapi.hotel.v3.SupplierType.S;
        _getAvailability_hotelRoomAvailabilityRequest.setSupplierType(_getAvailability_hotelRoomAvailabilityRequestSupplierType);
        _getAvailability_hotelRoomAvailabilityRequest.setRateKey("RateKey-2087679251");
        com.ean.wsapi.hotel.v3.RoomGroup _getAvailability_hotelRoomAvailabilityRequestRoomGroup = new com.ean.wsapi.hotel.v3.RoomGroup();
        java.util.List<com.ean.wsapi.hotel.v3.Room> _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoom = new java.util.ArrayList<com.ean.wsapi.hotel.v3.Room>();
        com.ean.wsapi.hotel.v3.Room _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1 = new com.ean.wsapi.hotel.v3.Room();
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.setNumberOfAdults(-816465104);
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.setNumberOfChildren(Integer.valueOf(-966422612));
        java.util.List<java.lang.Integer> _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1ChildAges = new java.util.ArrayList<java.lang.Integer>();
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.getChildAges().addAll(_getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1ChildAges);
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.setFirstName("FirstName829209694");
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.setLastName("LastName1121184298");
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.setBedTypeId("BedTypeId-920142422");
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.setBedTypeDescription("BedTypeDescription1057675257");
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.setNumberOfBeds(Integer.valueOf(2015578185));
        com.ean.wsapi.hotel.v3.SmokingPreference _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1SmokingPreference = com.ean.wsapi.hotel.v3.SmokingPreference.E;
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.setSmokingPreference(_getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1SmokingPreference);
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.setRoomTypeCode("RoomTypeCode208055855");
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.setRateCode("RateCode-1167198880");
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.setRateKey("RateKey625899772");
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.setRoomDescription("RoomDescription-532927310");
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1.setChargeableRate(Float.valueOf(0.74666375f));
        _getAvailability_hotelRoomAvailabilityRequestRoomGroupRoom.add(_getAvailability_hotelRoomAvailabilityRequestRoomGroupRoomVal1);
        _getAvailability_hotelRoomAvailabilityRequestRoomGroup.getRoom().addAll(_getAvailability_hotelRoomAvailabilityRequestRoomGroupRoom);
        _getAvailability_hotelRoomAvailabilityRequest.setRoomGroup(_getAvailability_hotelRoomAvailabilityRequestRoomGroup);
        java.util.List<com.ean.wsapi.hotel.v3.RatePlanType> _getAvailability_hotelRoomAvailabilityRequestRateType = new java.util.ArrayList<com.ean.wsapi.hotel.v3.RatePlanType>();
        com.ean.wsapi.hotel.v3.RatePlanType _getAvailability_hotelRoomAvailabilityRequestRateTypeVal1 = com.ean.wsapi.hotel.v3.RatePlanType.DIRECT_AGENCY;
        _getAvailability_hotelRoomAvailabilityRequestRateType.add(_getAvailability_hotelRoomAvailabilityRequestRateTypeVal1);
        _getAvailability_hotelRoomAvailabilityRequest.getRateType().addAll(_getAvailability_hotelRoomAvailabilityRequestRateType);
        _getAvailability_hotelRoomAvailabilityRequest.setRateCode("RateCode-1463240337");
        _getAvailability_hotelRoomAvailabilityRequest.setRoomTypeCode("RoomTypeCode410563433");
        _getAvailability_hotelRoomAvailabilityRequest.setIncludeRoomImages(Boolean.valueOf(false));
        com.ean.wsapi.hotel.v3.CouponData _getAvailability_hotelRoomAvailabilityRequestCouponData = new com.ean.wsapi.hotel.v3.CouponData();
        _getAvailability_hotelRoomAvailabilityRequestCouponData.setCode("Code2094544065");
        _getAvailability_hotelRoomAvailabilityRequestCouponData.setEmail("Email-1986971153");
        _getAvailability_hotelRoomAvailabilityRequest.setCouponData(_getAvailability_hotelRoomAvailabilityRequestCouponData);
        _getAvailability_hotelRoomAvailabilityRequest.setIncludeDetails(Boolean.valueOf(false));
        com.ean.wsapi.hotel.v3.MultiRoomAvailType _getAvailability_hotelRoomAvailabilityRequestMultiRoomAvail = com.ean.wsapi.hotel.v3.MultiRoomAvailType.NOT_SUPPPORTED;
        _getAvailability_hotelRoomAvailabilityRequest.setMultiRoomAvail(_getAvailability_hotelRoomAvailabilityRequestMultiRoomAvail);
        java.util.List<com.ean.wsapi.hotel.v3.HotelAvailOption> _getAvailability_hotelRoomAvailabilityRequestOptions = new java.util.ArrayList<com.ean.wsapi.hotel.v3.HotelAvailOption>();
        com.ean.wsapi.hotel.v3.HotelAvailOption _getAvailability_hotelRoomAvailabilityRequestOptionsVal1 = com.ean.wsapi.hotel.v3.HotelAvailOption.HOTEL_DETAILS;
        _getAvailability_hotelRoomAvailabilityRequestOptions.add(_getAvailability_hotelRoomAvailabilityRequestOptionsVal1);
        _getAvailability_hotelRoomAvailabilityRequest.getOptions().addAll(_getAvailability_hotelRoomAvailabilityRequestOptions);
        com.ean.wsapi.hotel.v3.HotelRoomAvailabilityResponse _getAvailability__return = port.getAvailability(_getAvailability_hotelRoomAvailabilityRequest);
        System.out.println("getAvailability.result=" + _getAvailability__return);


        }
        {
        System.out.println("Invoking getRoomImage...");
        com.ean.wsapi.hotel.v3.HotelRoomImageRequest _getRoomImage_hotelRoomImageRequest = new com.ean.wsapi.hotel.v3.HotelRoomImageRequest();
        _getRoomImage_hotelRoomImageRequest.setApiKey("ApiKey1072056132");
        _getRoomImage_hotelRoomImageRequest.setCid(-2984010656200853819l);
        _getRoomImage_hotelRoomImageRequest.setCustomerIpAddress("CustomerIpAddress1916328089");
        _getRoomImage_hotelRoomImageRequest.setCustomerSessionId("CustomerSessionId764112917");
        _getRoomImage_hotelRoomImageRequest.setCustomerUserAgent("CustomerUserAgent-1505937829");
        com.ean.wsapi.hotel.v3.LocaleType _getRoomImage_hotelRoomImageRequestLocale = com.ean.wsapi.hotel.v3.LocaleType.PT_BR;
        _getRoomImage_hotelRoomImageRequest.setLocale(_getRoomImage_hotelRoomImageRequestLocale);
        _getRoomImage_hotelRoomImageRequest.setCurrencyCode("CurrencyCode1344398776");
        java.util.List<com.ean.wsapi.hotel.v3.MapEntry> _getRoomImage_hotelRoomImageRequestAdditionalData = new java.util.ArrayList<com.ean.wsapi.hotel.v3.MapEntry>();
        com.ean.wsapi.hotel.v3.MapEntry _getRoomImage_hotelRoomImageRequestAdditionalDataVal1 = new com.ean.wsapi.hotel.v3.MapEntry();
        _getRoomImage_hotelRoomImageRequestAdditionalDataVal1.setKey("Key193076363");
        _getRoomImage_hotelRoomImageRequestAdditionalDataVal1.setValue("Value-223805937");
        _getRoomImage_hotelRoomImageRequestAdditionalData.add(_getRoomImage_hotelRoomImageRequestAdditionalDataVal1);
        _getRoomImage_hotelRoomImageRequest.getAdditionalData().addAll(_getRoomImage_hotelRoomImageRequestAdditionalData);
        _getRoomImage_hotelRoomImageRequest.setSig("Sig-60277290");
        _getRoomImage_hotelRoomImageRequest.setDebug(Boolean.valueOf(true));
        _getRoomImage_hotelRoomImageRequest.setTest(Boolean.valueOf(true));
        _getRoomImage_hotelRoomImageRequest.setMinorRev(Integer.valueOf(809882091));
        _getRoomImage_hotelRoomImageRequest.setHotelId(3375832974271712266l);
        _getRoomImage_hotelRoomImageRequest.setRoomTypeId("RoomTypeId786755115");
        com.ean.wsapi.hotel.v3.HotelRoomImageResponse _getRoomImage__return = port.getRoomImage(_getRoomImage_hotelRoomImageRequest);
        System.out.println("getRoomImage.result=" + _getRoomImage__return);


        }
        {
        System.out.println("Invoking getCancellation...");
        com.ean.wsapi.hotel.v3.HotelRoomCancellationRequest _getCancellation_hotelRoomCancellationRequest = new com.ean.wsapi.hotel.v3.HotelRoomCancellationRequest();
        _getCancellation_hotelRoomCancellationRequest.setApiKey("ApiKey-1190070790");
        _getCancellation_hotelRoomCancellationRequest.setCid(3655750829476739114l);
        _getCancellation_hotelRoomCancellationRequest.setCustomerIpAddress("CustomerIpAddress-1013561483");
        _getCancellation_hotelRoomCancellationRequest.setCustomerSessionId("CustomerSessionId205976121");
        _getCancellation_hotelRoomCancellationRequest.setCustomerUserAgent("CustomerUserAgent-1088434380");
        com.ean.wsapi.hotel.v3.LocaleType _getCancellation_hotelRoomCancellationRequestLocale = com.ean.wsapi.hotel.v3.LocaleType.ES_ES;
        _getCancellation_hotelRoomCancellationRequest.setLocale(_getCancellation_hotelRoomCancellationRequestLocale);
        _getCancellation_hotelRoomCancellationRequest.setCurrencyCode("CurrencyCode1911266221");
        java.util.List<com.ean.wsapi.hotel.v3.MapEntry> _getCancellation_hotelRoomCancellationRequestAdditionalData = new java.util.ArrayList<com.ean.wsapi.hotel.v3.MapEntry>();
        com.ean.wsapi.hotel.v3.MapEntry _getCancellation_hotelRoomCancellationRequestAdditionalDataVal1 = new com.ean.wsapi.hotel.v3.MapEntry();
        _getCancellation_hotelRoomCancellationRequestAdditionalDataVal1.setKey("Key784685164");
        _getCancellation_hotelRoomCancellationRequestAdditionalDataVal1.setValue("Value1858393140");
        _getCancellation_hotelRoomCancellationRequestAdditionalData.add(_getCancellation_hotelRoomCancellationRequestAdditionalDataVal1);
        _getCancellation_hotelRoomCancellationRequest.getAdditionalData().addAll(_getCancellation_hotelRoomCancellationRequestAdditionalData);
        _getCancellation_hotelRoomCancellationRequest.setSig("Sig-1613047744");
        _getCancellation_hotelRoomCancellationRequest.setDebug(Boolean.valueOf(true));
        _getCancellation_hotelRoomCancellationRequest.setTest(Boolean.valueOf(true));
        _getCancellation_hotelRoomCancellationRequest.setMinorRev(Integer.valueOf(653849454));
        _getCancellation_hotelRoomCancellationRequest.setItineraryId(-5042619595517829185l);
        _getCancellation_hotelRoomCancellationRequest.setEmail("Email604705354");
        _getCancellation_hotelRoomCancellationRequest.setConfirmationNumber("ConfirmationNumber826808083");
        _getCancellation_hotelRoomCancellationRequest.setReason("Reason-622220663");
        com.ean.wsapi.hotel.v3.HotelRoomCancellationResponse _getCancellation__return = port.getCancellation(_getCancellation_hotelRoomCancellationRequest);
        System.out.println("getCancellation.result=" + _getCancellation__return);


        }
        {
        System.out.println("Invoking getItinerary...");
        com.ean.wsapi.hotel.v3.HotelItineraryRequest _getItinerary_hotelItineraryRequest = new com.ean.wsapi.hotel.v3.HotelItineraryRequest();
        _getItinerary_hotelItineraryRequest.setApiKey("ApiKey737144044");
        _getItinerary_hotelItineraryRequest.setCid(-8244850349909568227l);
        _getItinerary_hotelItineraryRequest.setCustomerIpAddress("CustomerIpAddress1122160610");
        _getItinerary_hotelItineraryRequest.setCustomerSessionId("CustomerSessionId1203867827");
        _getItinerary_hotelItineraryRequest.setCustomerUserAgent("CustomerUserAgent-567530164");
        com.ean.wsapi.hotel.v3.LocaleType _getItinerary_hotelItineraryRequestLocale = com.ean.wsapi.hotel.v3.LocaleType.DA_DK;
        _getItinerary_hotelItineraryRequest.setLocale(_getItinerary_hotelItineraryRequestLocale);
        _getItinerary_hotelItineraryRequest.setCurrencyCode("CurrencyCode1821677461");
        java.util.List<com.ean.wsapi.hotel.v3.MapEntry> _getItinerary_hotelItineraryRequestAdditionalData = new java.util.ArrayList<com.ean.wsapi.hotel.v3.MapEntry>();
        com.ean.wsapi.hotel.v3.MapEntry _getItinerary_hotelItineraryRequestAdditionalDataVal1 = new com.ean.wsapi.hotel.v3.MapEntry();
        _getItinerary_hotelItineraryRequestAdditionalDataVal1.setKey("Key-1012367386");
        _getItinerary_hotelItineraryRequestAdditionalDataVal1.setValue("Value-61752549");
        _getItinerary_hotelItineraryRequestAdditionalData.add(_getItinerary_hotelItineraryRequestAdditionalDataVal1);
        _getItinerary_hotelItineraryRequest.getAdditionalData().addAll(_getItinerary_hotelItineraryRequestAdditionalData);
        _getItinerary_hotelItineraryRequest.setSig("Sig593845506");
        _getItinerary_hotelItineraryRequest.setDebug(Boolean.valueOf(false));
        _getItinerary_hotelItineraryRequest.setTest(Boolean.valueOf(true));
        _getItinerary_hotelItineraryRequest.setMinorRev(Integer.valueOf(-1146677635));
        _getItinerary_hotelItineraryRequest.setItineraryId(Long.valueOf(-2532252939966952087l));
        _getItinerary_hotelItineraryRequest.setLastName("LastName-270244726");
        _getItinerary_hotelItineraryRequest.setEmail("Email1758894537");
        _getItinerary_hotelItineraryRequest.setAffiliateConfirmationId("AffiliateConfirmationId-826761500");
        _getItinerary_hotelItineraryRequest.setAffiliateCustomerId("AffiliateCustomerId-2033948193");
        _getItinerary_hotelItineraryRequest.setCreditCardNumber("CreditCardNumber2055114688");
        com.ean.wsapi.hotel.v3.ItineraryQuery _getItinerary_hotelItineraryRequestItineraryQuery = new com.ean.wsapi.hotel.v3.ItineraryQuery();
        _getItinerary_hotelItineraryRequestItineraryQuery.setCreationDateStart("CreationDateStart1804612797");
        _getItinerary_hotelItineraryRequestItineraryQuery.setCreationDateEnd("CreationDateEnd372539251");
        _getItinerary_hotelItineraryRequestItineraryQuery.setDepartureDateStart("DepartureDateStart1214855678");
        _getItinerary_hotelItineraryRequestItineraryQuery.setDepartureDateEnd("DepartureDateEnd917491060");
        _getItinerary_hotelItineraryRequestItineraryQuery.setIncludeChildAffiliates(Boolean.valueOf(true));
        _getItinerary_hotelItineraryRequest.setItineraryQuery(_getItinerary_hotelItineraryRequestItineraryQuery);
        java.util.List<java.lang.String> _getItinerary_hotelItineraryRequestConfirmationExtras = new java.util.ArrayList<java.lang.String>();
        java.lang.String _getItinerary_hotelItineraryRequestConfirmationExtrasVal1 = "_getItinerary_hotelItineraryRequestConfirmationExtrasVal1801664010";
        _getItinerary_hotelItineraryRequestConfirmationExtras.add(_getItinerary_hotelItineraryRequestConfirmationExtrasVal1);
        _getItinerary_hotelItineraryRequest.getConfirmationExtras().addAll(_getItinerary_hotelItineraryRequestConfirmationExtras);
        _getItinerary_hotelItineraryRequest.setSupplierConfirmationNumber("SupplierConfirmationNumber-156496195");
        com.ean.wsapi.hotel.v3.HotelItineraryResponse _getItinerary__return = port.getItinerary(_getItinerary_hotelItineraryRequest);
        System.out.println("getItinerary.result=" + _getItinerary__return);


        }
        {
        System.out.println("Invoking getAlternateProperties...");
        com.ean.wsapi.hotel.v3.AlternatePropertyListRequest _getAlternateProperties_alternatePropertyListRequest = new com.ean.wsapi.hotel.v3.AlternatePropertyListRequest();
        _getAlternateProperties_alternatePropertyListRequest.setApiKey("ApiKey6699313");
        _getAlternateProperties_alternatePropertyListRequest.setCid(-1288083100292675444l);
        _getAlternateProperties_alternatePropertyListRequest.setCustomerIpAddress("CustomerIpAddress1208686017");
        _getAlternateProperties_alternatePropertyListRequest.setCustomerSessionId("CustomerSessionId-1149445982");
        _getAlternateProperties_alternatePropertyListRequest.setCustomerUserAgent("CustomerUserAgent1520783670");
        com.ean.wsapi.hotel.v3.LocaleType _getAlternateProperties_alternatePropertyListRequestLocale = com.ean.wsapi.hotel.v3.LocaleType.EN_GB;
        _getAlternateProperties_alternatePropertyListRequest.setLocale(_getAlternateProperties_alternatePropertyListRequestLocale);
        _getAlternateProperties_alternatePropertyListRequest.setCurrencyCode("CurrencyCode1798548754");
        java.util.List<com.ean.wsapi.hotel.v3.MapEntry> _getAlternateProperties_alternatePropertyListRequestAdditionalData = new java.util.ArrayList<com.ean.wsapi.hotel.v3.MapEntry>();
        com.ean.wsapi.hotel.v3.MapEntry _getAlternateProperties_alternatePropertyListRequestAdditionalDataVal1 = new com.ean.wsapi.hotel.v3.MapEntry();
        _getAlternateProperties_alternatePropertyListRequestAdditionalDataVal1.setKey("Key-899778764");
        _getAlternateProperties_alternatePropertyListRequestAdditionalDataVal1.setValue("Value-1717156853");
        _getAlternateProperties_alternatePropertyListRequestAdditionalData.add(_getAlternateProperties_alternatePropertyListRequestAdditionalDataVal1);
        _getAlternateProperties_alternatePropertyListRequest.getAdditionalData().addAll(_getAlternateProperties_alternatePropertyListRequestAdditionalData);
        _getAlternateProperties_alternatePropertyListRequest.setSig("Sig72720294");
        _getAlternateProperties_alternatePropertyListRequest.setDebug(Boolean.valueOf(false));
        _getAlternateProperties_alternatePropertyListRequest.setTest(Boolean.valueOf(false));
        _getAlternateProperties_alternatePropertyListRequest.setMinorRev(Integer.valueOf(88219555));
        _getAlternateProperties_alternatePropertyListRequest.setOriginalHotelId(5181411016896566186l);
        _getAlternateProperties_alternatePropertyListRequest.setArrivalDate("ArrivalDate1889935825");
        _getAlternateProperties_alternatePropertyListRequest.setDepartureDate("DepartureDate-866087299");
        _getAlternateProperties_alternatePropertyListRequest.setOriginalAverageNightlyRate(0.31486678f);
        com.ean.wsapi.hotel.v3.RoomGroup _getAlternateProperties_alternatePropertyListRequestRoomGroup = new com.ean.wsapi.hotel.v3.RoomGroup();
        java.util.List<com.ean.wsapi.hotel.v3.Room> _getAlternateProperties_alternatePropertyListRequestRoomGroupRoom = new java.util.ArrayList<com.ean.wsapi.hotel.v3.Room>();
        com.ean.wsapi.hotel.v3.Room _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1 = new com.ean.wsapi.hotel.v3.Room();
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.setNumberOfAdults(-366714939);
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.setNumberOfChildren(Integer.valueOf(-602560060));
        java.util.List<java.lang.Integer> _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1ChildAges = new java.util.ArrayList<java.lang.Integer>();
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.getChildAges().addAll(_getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1ChildAges);
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.setFirstName("FirstName365163083");
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.setLastName("LastName889475890");
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.setBedTypeId("BedTypeId790225921");
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.setBedTypeDescription("BedTypeDescription-1572503631");
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.setNumberOfBeds(Integer.valueOf(-924377660));
        com.ean.wsapi.hotel.v3.SmokingPreference _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1SmokingPreference = com.ean.wsapi.hotel.v3.SmokingPreference.NS;
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.setSmokingPreference(_getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1SmokingPreference);
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.setRoomTypeCode("RoomTypeCode-1215958620");
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.setRateCode("RateCode-1945575124");
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.setRateKey("RateKey-1457760328");
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.setRoomDescription("RoomDescription1321798680");
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1.setChargeableRate(Float.valueOf(0.19926763f));
        _getAlternateProperties_alternatePropertyListRequestRoomGroupRoom.add(_getAlternateProperties_alternatePropertyListRequestRoomGroupRoomVal1);
        _getAlternateProperties_alternatePropertyListRequestRoomGroup.getRoom().addAll(_getAlternateProperties_alternatePropertyListRequestRoomGroupRoom);
        _getAlternateProperties_alternatePropertyListRequest.setRoomGroup(_getAlternateProperties_alternatePropertyListRequestRoomGroup);
        com.ean.wsapi.hotel.v3.RatePlanType _getAlternateProperties_alternatePropertyListRequestRateType = com.ean.wsapi.hotel.v3.RatePlanType.DIRECT_AGENCY;
        _getAlternateProperties_alternatePropertyListRequest.setRateType(_getAlternateProperties_alternatePropertyListRequestRateType);
        _getAlternateProperties_alternatePropertyListRequest.setPriceType(Integer.valueOf(2016476004));
        com.ean.wsapi.hotel.v3.AlternatePropertyListResponse _getAlternateProperties__return = port.getAlternateProperties(_getAlternateProperties_alternatePropertyListRequest);
        System.out.println("getAlternateProperties.result=" + _getAlternateProperties__return);


        }
        {
        System.out.println("Invoking getPing...");
        com.ean.wsapi.hotel.v3.PingRequest _getPing_pingRequest = new com.ean.wsapi.hotel.v3.PingRequest();
        _getPing_pingRequest.setApiKey("ApiKey-1430226570");
        _getPing_pingRequest.setCid(-401947461539037503l);
        _getPing_pingRequest.setCustomerIpAddress("CustomerIpAddress-1774564857");
        _getPing_pingRequest.setCustomerSessionId("CustomerSessionId834459883");
        _getPing_pingRequest.setCustomerUserAgent("CustomerUserAgent1116472432");
        com.ean.wsapi.hotel.v3.LocaleType _getPing_pingRequestLocale = com.ean.wsapi.hotel.v3.LocaleType.ZH_CN;
        _getPing_pingRequest.setLocale(_getPing_pingRequestLocale);
        _getPing_pingRequest.setCurrencyCode("CurrencyCode1902461364");
        java.util.List<com.ean.wsapi.hotel.v3.MapEntry> _getPing_pingRequestAdditionalData = new java.util.ArrayList<com.ean.wsapi.hotel.v3.MapEntry>();
        com.ean.wsapi.hotel.v3.MapEntry _getPing_pingRequestAdditionalDataVal1 = new com.ean.wsapi.hotel.v3.MapEntry();
        _getPing_pingRequestAdditionalDataVal1.setKey("Key-917792415");
        _getPing_pingRequestAdditionalDataVal1.setValue("Value-1237073463");
        _getPing_pingRequestAdditionalData.add(_getPing_pingRequestAdditionalDataVal1);
        _getPing_pingRequest.getAdditionalData().addAll(_getPing_pingRequestAdditionalData);
        _getPing_pingRequest.setSig("Sig824277241");
        _getPing_pingRequest.setDebug(Boolean.valueOf(true));
        _getPing_pingRequest.setTest(Boolean.valueOf(false));
        _getPing_pingRequest.setMinorRev(Integer.valueOf(-1689732215));
        _getPing_pingRequest.setEcho("Echo-513378906");
        com.ean.wsapi.hotel.v3.PingResponse _getPing__return = port.getPing(_getPing_pingRequest);
        System.out.println("getPing.result=" + _getPing__return);


        }
        {
        System.out.println("Invoking getGeoLocation...");
        com.ean.wsapi.hotel.v3.LocationInfoRequest _getGeoLocation_locationInfoRequest = new com.ean.wsapi.hotel.v3.LocationInfoRequest();
        _getGeoLocation_locationInfoRequest.setApiKey("ApiKey-1259019679");
        _getGeoLocation_locationInfoRequest.setCid(-7929968384804057627l);
        _getGeoLocation_locationInfoRequest.setCustomerIpAddress("CustomerIpAddress-1671801685");
        _getGeoLocation_locationInfoRequest.setCustomerSessionId("CustomerSessionId-1405002074");
        _getGeoLocation_locationInfoRequest.setCustomerUserAgent("CustomerUserAgent-818710296");
        com.ean.wsapi.hotel.v3.LocaleType _getGeoLocation_locationInfoRequestLocale = com.ean.wsapi.hotel.v3.LocaleType.AR_SA;
        _getGeoLocation_locationInfoRequest.setLocale(_getGeoLocation_locationInfoRequestLocale);
        _getGeoLocation_locationInfoRequest.setCurrencyCode("CurrencyCode-223741560");
        java.util.List<com.ean.wsapi.hotel.v3.MapEntry> _getGeoLocation_locationInfoRequestAdditionalData = new java.util.ArrayList<com.ean.wsapi.hotel.v3.MapEntry>();
        com.ean.wsapi.hotel.v3.MapEntry _getGeoLocation_locationInfoRequestAdditionalDataVal1 = new com.ean.wsapi.hotel.v3.MapEntry();
        _getGeoLocation_locationInfoRequestAdditionalDataVal1.setKey("Key-38355734");
        _getGeoLocation_locationInfoRequestAdditionalDataVal1.setValue("Value1969768378");
        _getGeoLocation_locationInfoRequestAdditionalData.add(_getGeoLocation_locationInfoRequestAdditionalDataVal1);
        _getGeoLocation_locationInfoRequest.getAdditionalData().addAll(_getGeoLocation_locationInfoRequestAdditionalData);
        _getGeoLocation_locationInfoRequest.setSig("Sig-639595817");
        _getGeoLocation_locationInfoRequest.setDebug(Boolean.valueOf(true));
        _getGeoLocation_locationInfoRequest.setTest(Boolean.valueOf(true));
        _getGeoLocation_locationInfoRequest.setMinorRev(Integer.valueOf(214225758));
        _getGeoLocation_locationInfoRequest.setAddress("Address1684411527");
        _getGeoLocation_locationInfoRequest.setCity("City-25436388");
        _getGeoLocation_locationInfoRequest.setStateProvinceCode("StateProvinceCode1744831777");
        _getGeoLocation_locationInfoRequest.setCountryCode("CountryCode2086263835");
        _getGeoLocation_locationInfoRequest.setPostalCode("PostalCode62045868");
        _getGeoLocation_locationInfoRequest.setDestinationString("DestinationString-845312303");
        _getGeoLocation_locationInfoRequest.setDestinationId("DestinationId1543782310");
        _getGeoLocation_locationInfoRequest.setIgnoreSearchWeight(Boolean.valueOf(false));
        _getGeoLocation_locationInfoRequest.setUseGeocoder(Boolean.valueOf(false));
        _getGeoLocation_locationInfoRequest.setType("Type1641099108");
        com.ean.wsapi.hotel.v3.LocationInfoResponse _getGeoLocation__return = port.getGeoLocation(_getGeoLocation_locationInfoRequest);
        System.out.println("getGeoLocation.result=" + _getGeoLocation__return);


        }
        {
        System.out.println("Invoking getPaymentInfo...");
        com.ean.wsapi.hotel.v3.V3HotelPaymentRequest _getPaymentInfo_hotelPaymentRequest = new com.ean.wsapi.hotel.v3.V3HotelPaymentRequest();
        _getPaymentInfo_hotelPaymentRequest.setApiKey("ApiKey1945303472");
        _getPaymentInfo_hotelPaymentRequest.setCid(4102387862530287716l);
        _getPaymentInfo_hotelPaymentRequest.setCustomerIpAddress("CustomerIpAddress517127018");
        _getPaymentInfo_hotelPaymentRequest.setCustomerSessionId("CustomerSessionId1523295832");
        _getPaymentInfo_hotelPaymentRequest.setCustomerUserAgent("CustomerUserAgent1698861277");
        com.ean.wsapi.hotel.v3.LocaleType _getPaymentInfo_hotelPaymentRequestLocale = com.ean.wsapi.hotel.v3.LocaleType.HU_HU;
        _getPaymentInfo_hotelPaymentRequest.setLocale(_getPaymentInfo_hotelPaymentRequestLocale);
        _getPaymentInfo_hotelPaymentRequest.setCurrencyCode("CurrencyCode-402193018");
        java.util.List<com.ean.wsapi.hotel.v3.MapEntry> _getPaymentInfo_hotelPaymentRequestAdditionalData = new java.util.ArrayList<com.ean.wsapi.hotel.v3.MapEntry>();
        com.ean.wsapi.hotel.v3.MapEntry _getPaymentInfo_hotelPaymentRequestAdditionalDataVal1 = new com.ean.wsapi.hotel.v3.MapEntry();
        _getPaymentInfo_hotelPaymentRequestAdditionalDataVal1.setKey("Key360573586");
        _getPaymentInfo_hotelPaymentRequestAdditionalDataVal1.setValue("Value-1271781535");
        _getPaymentInfo_hotelPaymentRequestAdditionalData.add(_getPaymentInfo_hotelPaymentRequestAdditionalDataVal1);
        _getPaymentInfo_hotelPaymentRequest.getAdditionalData().addAll(_getPaymentInfo_hotelPaymentRequestAdditionalData);
        _getPaymentInfo_hotelPaymentRequest.setSig("Sig-1132680589");
        _getPaymentInfo_hotelPaymentRequest.setDebug(Boolean.valueOf(false));
        _getPaymentInfo_hotelPaymentRequest.setTest(Boolean.valueOf(true));
        _getPaymentInfo_hotelPaymentRequest.setMinorRev(Integer.valueOf(48537804));
        _getPaymentInfo_hotelPaymentRequest.setHotelId(Long.valueOf(2491072455542386508l));
        com.ean.wsapi.hotel.v3.SupplierType _getPaymentInfo_hotelPaymentRequestSupplierType = com.ean.wsapi.hotel.v3.SupplierType.W;
        _getPaymentInfo_hotelPaymentRequest.setSupplierType(_getPaymentInfo_hotelPaymentRequestSupplierType);
        com.ean.wsapi.hotel.v3.RatePlanType _getPaymentInfo_hotelPaymentRequestRateType = com.ean.wsapi.hotel.v3.RatePlanType.MERCHANT_PACKAGE;
        _getPaymentInfo_hotelPaymentRequest.setRateType(_getPaymentInfo_hotelPaymentRequestRateType);
        com.ean.wsapi.hotel.v3.HotelPaymentResponse _getPaymentInfo__return = port.getPaymentInfo(_getPaymentInfo_hotelPaymentRequest);
        System.out.println("getPaymentInfo.result=" + _getPaymentInfo__return);


        }
        {
        System.out.println("Invoking getReservation...");
        com.ean.wsapi.hotel.v3.HotelRoomReservationRequest _getReservation_hotelRoomReservationRequest = new com.ean.wsapi.hotel.v3.HotelRoomReservationRequest();
        _getReservation_hotelRoomReservationRequest.setApiKey("ApiKey-2057337534");
        _getReservation_hotelRoomReservationRequest.setCid(397896973537283854l);
        _getReservation_hotelRoomReservationRequest.setCustomerIpAddress("CustomerIpAddress1604021669");
        _getReservation_hotelRoomReservationRequest.setCustomerSessionId("CustomerSessionId1365409813");
        _getReservation_hotelRoomReservationRequest.setCustomerUserAgent("CustomerUserAgent-2097914459");
        com.ean.wsapi.hotel.v3.LocaleType _getReservation_hotelRoomReservationRequestLocale = com.ean.wsapi.hotel.v3.LocaleType.ZH_CN;
        _getReservation_hotelRoomReservationRequest.setLocale(_getReservation_hotelRoomReservationRequestLocale);
        _getReservation_hotelRoomReservationRequest.setCurrencyCode("CurrencyCode-681089342");
        java.util.List<com.ean.wsapi.hotel.v3.MapEntry> _getReservation_hotelRoomReservationRequestAdditionalData = new java.util.ArrayList<com.ean.wsapi.hotel.v3.MapEntry>();
        com.ean.wsapi.hotel.v3.MapEntry _getReservation_hotelRoomReservationRequestAdditionalDataVal1 = new com.ean.wsapi.hotel.v3.MapEntry();
        _getReservation_hotelRoomReservationRequestAdditionalDataVal1.setKey("Key-349757009");
        _getReservation_hotelRoomReservationRequestAdditionalDataVal1.setValue("Value685579354");
        _getReservation_hotelRoomReservationRequestAdditionalData.add(_getReservation_hotelRoomReservationRequestAdditionalDataVal1);
        _getReservation_hotelRoomReservationRequest.getAdditionalData().addAll(_getReservation_hotelRoomReservationRequestAdditionalData);
        _getReservation_hotelRoomReservationRequest.setSig("Sig-713772294");
        _getReservation_hotelRoomReservationRequest.setDebug(Boolean.valueOf(true));
        _getReservation_hotelRoomReservationRequest.setTest(Boolean.valueOf(true));
        _getReservation_hotelRoomReservationRequest.setMinorRev(Integer.valueOf(-1909332702));
        _getReservation_hotelRoomReservationRequest.setHotelId(-9183099786014728479l);
        _getReservation_hotelRoomReservationRequest.setArrivalDate("ArrivalDate-1181914231");
        _getReservation_hotelRoomReservationRequest.setDepartureDate("DepartureDate165206998");
        com.ean.wsapi.hotel.v3.SupplierType _getReservation_hotelRoomReservationRequestSupplierType = com.ean.wsapi.hotel.v3.SupplierType.E;
        _getReservation_hotelRoomReservationRequest.setSupplierType(_getReservation_hotelRoomReservationRequestSupplierType);
        _getReservation_hotelRoomReservationRequest.setRateKey("RateKey1468571280");
        _getReservation_hotelRoomReservationRequest.setRoomTypeCode("RoomTypeCode-593269712");
        _getReservation_hotelRoomReservationRequest.setRoomDescription("RoomDescription262868601");
        _getReservation_hotelRoomReservationRequest.setRateCode("RateCode137483126");
        _getReservation_hotelRoomReservationRequest.setSendReservationEmail(true);
        _getReservation_hotelRoomReservationRequest.setFrequentGuestNumber("FrequentGuestNumber1434942485");
        _getReservation_hotelRoomReservationRequest.setAffiliateConfirmationId("AffiliateConfirmationId-947141219");
        _getReservation_hotelRoomReservationRequest.setAffiliateCustomerId("AffiliateCustomerId-1332616568");
        _getReservation_hotelRoomReservationRequest.setItineraryId(Long.valueOf(4717062834473476754l));
        _getReservation_hotelRoomReservationRequest.setChargeableRate(0.03897041f);
        _getReservation_hotelRoomReservationRequest.setSpecialInformation("SpecialInformation-1498880209");
        com.ean.wsapi.hotel.v3.RoomGroup _getReservation_hotelRoomReservationRequestRoomGroup = new com.ean.wsapi.hotel.v3.RoomGroup();
        java.util.List<com.ean.wsapi.hotel.v3.Room> _getReservation_hotelRoomReservationRequestRoomGroupRoom = new java.util.ArrayList<com.ean.wsapi.hotel.v3.Room>();
        com.ean.wsapi.hotel.v3.Room _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1 = new com.ean.wsapi.hotel.v3.Room();
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.setNumberOfAdults(297387073);
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.setNumberOfChildren(Integer.valueOf(1135236236));
        java.util.List<java.lang.Integer> _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1ChildAges = new java.util.ArrayList<java.lang.Integer>();
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.getChildAges().addAll(_getReservation_hotelRoomReservationRequestRoomGroupRoomVal1ChildAges);
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.setFirstName("FirstName259243660");
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.setLastName("LastName1506062347");
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.setBedTypeId("BedTypeId1540243638");
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.setBedTypeDescription("BedTypeDescription987921823");
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.setNumberOfBeds(Integer.valueOf(-1021443771));
        com.ean.wsapi.hotel.v3.SmokingPreference _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1SmokingPreference = com.ean.wsapi.hotel.v3.SmokingPreference.E;
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.setSmokingPreference(_getReservation_hotelRoomReservationRequestRoomGroupRoomVal1SmokingPreference);
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.setRoomTypeCode("RoomTypeCode-1817832526");
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.setRateCode("RateCode2138859674");
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.setRateKey("RateKey1000382179");
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.setRoomDescription("RoomDescription697809131");
        _getReservation_hotelRoomReservationRequestRoomGroupRoomVal1.setChargeableRate(Float.valueOf(0.3908456f));
        _getReservation_hotelRoomReservationRequestRoomGroupRoom.add(_getReservation_hotelRoomReservationRequestRoomGroupRoomVal1);
        _getReservation_hotelRoomReservationRequestRoomGroup.getRoom().addAll(_getReservation_hotelRoomReservationRequestRoomGroupRoom);
        _getReservation_hotelRoomReservationRequest.setRoomGroup(_getReservation_hotelRoomReservationRequestRoomGroup);
        com.ean.wsapi.hotel.v3.RatePlanType _getReservation_hotelRoomReservationRequestRateType = com.ean.wsapi.hotel.v3.RatePlanType.MERCHANT_PACKAGE;
        _getReservation_hotelRoomReservationRequest.setRateType(_getReservation_hotelRoomReservationRequestRateType);
        com.ean.wsapi.hotel.v3.ReservationInfo _getReservation_hotelRoomReservationRequestReservationInfo = new com.ean.wsapi.hotel.v3.ReservationInfo();
        _getReservation_hotelRoomReservationRequestReservationInfo.setEmail("Email1900664153");
        _getReservation_hotelRoomReservationRequestReservationInfo.setFirstName("FirstName447285822");
        _getReservation_hotelRoomReservationRequestReservationInfo.setLastName("LastName1922555192");
        _getReservation_hotelRoomReservationRequestReservationInfo.setHomePhone("HomePhone-427951903");
        _getReservation_hotelRoomReservationRequestReservationInfo.setWorkPhone("WorkPhone-728646972");
        _getReservation_hotelRoomReservationRequestReservationInfo.setExtension("Extension686277962");
        _getReservation_hotelRoomReservationRequestReservationInfo.setFaxPhone("FaxPhone1137043824");
        _getReservation_hotelRoomReservationRequestReservationInfo.setCompanyName("CompanyName1971208519");
        _getReservation_hotelRoomReservationRequestReservationInfo.setCreditCardType("CreditCardType104919433");
        _getReservation_hotelRoomReservationRequestReservationInfo.setCreditCardNumber("CreditCardNumber706551159");
        _getReservation_hotelRoomReservationRequestReservationInfo.setCreditCardIdentifier("CreditCardIdentifier595110101");
        _getReservation_hotelRoomReservationRequestReservationInfo.setCreditCardExpirationMonth("CreditCardExpirationMonth-923648652");
        _getReservation_hotelRoomReservationRequestReservationInfo.setCreditCardExpirationYear("CreditCardExpirationYear554433210");
        _getReservation_hotelRoomReservationRequestReservationInfo.setCreditCardStartDate("CreditCardStartDate1806935007");
        _getReservation_hotelRoomReservationRequestReservationInfo.setCreditCardIssueNumber("CreditCardIssueNumber-1671868862");
        _getReservation_hotelRoomReservationRequestReservationInfo.setCreditCardPasHttpUserAgent("CreditCardPasHttpUserAgent-1327370068");
        _getReservation_hotelRoomReservationRequestReservationInfo.setCreditCardPasHttpAccept("CreditCardPasHttpAccept-442053955");
        _getReservation_hotelRoomReservationRequestReservationInfo.setCreditCardPasPaRes("CreditCardPasPaRes1305012512");
        java.util.List<java.lang.String> _getReservation_hotelRoomReservationRequestReservationInfoEmailItineraryList = new java.util.ArrayList<java.lang.String>();
        java.lang.String _getReservation_hotelRoomReservationRequestReservationInfoEmailItineraryListVal1 = "_getReservation_hotelRoomReservationRequestReservationInfoEmailItineraryListVal1563463632";
        _getReservation_hotelRoomReservationRequestReservationInfoEmailItineraryList.add(_getReservation_hotelRoomReservationRequestReservationInfoEmailItineraryListVal1);
        _getReservation_hotelRoomReservationRequestReservationInfo.getEmailItineraryList().addAll(_getReservation_hotelRoomReservationRequestReservationInfoEmailItineraryList);
        _getReservation_hotelRoomReservationRequest.setReservationInfo(_getReservation_hotelRoomReservationRequestReservationInfo);
        com.ean.wsapi.hotel.v3.AddressInfo _getReservation_hotelRoomReservationRequestAddressInfo = new com.ean.wsapi.hotel.v3.AddressInfo();
        _getReservation_hotelRoomReservationRequestAddressInfo.setAddress1("Address1699621468");
        _getReservation_hotelRoomReservationRequestAddressInfo.setAddress2("Address2-1268087761");
        _getReservation_hotelRoomReservationRequestAddressInfo.setAddress3("Address31993795698");
        _getReservation_hotelRoomReservationRequestAddressInfo.setCity("City2091726424");
        _getReservation_hotelRoomReservationRequestAddressInfo.setStateProvinceCode("StateProvinceCode1649821517");
        _getReservation_hotelRoomReservationRequestAddressInfo.setCountryCode("CountryCode-1126073083");
        _getReservation_hotelRoomReservationRequestAddressInfo.setPostalCode("PostalCode-736063493");
        _getReservation_hotelRoomReservationRequest.setAddressInfo(_getReservation_hotelRoomReservationRequestAddressInfo);
        com.ean.wsapi.hotel.v3.CouponData _getReservation_hotelRoomReservationRequestCouponData = new com.ean.wsapi.hotel.v3.CouponData();
        _getReservation_hotelRoomReservationRequestCouponData.setCode("Code-1350196939");
        _getReservation_hotelRoomReservationRequestCouponData.setEmail("Email1436239895");
        _getReservation_hotelRoomReservationRequest.setCouponData(_getReservation_hotelRoomReservationRequestCouponData);
        com.ean.wsapi.hotel.v3.MultiRoomResType _getReservation_hotelRoomReservationRequestMultiRoomRes = com.ean.wsapi.hotel.v3.MultiRoomResType.NOT_SUPPPORTED;
        _getReservation_hotelRoomReservationRequest.setMultiRoomRes(_getReservation_hotelRoomReservationRequestMultiRoomRes);
        com.ean.wsapi.hotel.v3.HotelRoomReservationResponse _getReservation__return = port.getReservation(_getReservation_hotelRoomReservationRequest);
        System.out.println("getReservation.result=" + _getReservation__return);


        }
        {
        System.out.println("Invoking getInformation...");
        com.ean.wsapi.hotel.v3.HotelInformationRequest _getInformation_hotelInformationRequest = new com.ean.wsapi.hotel.v3.HotelInformationRequest();
        _getInformation_hotelInformationRequest.setApiKey("ApiKey1642986081");
        _getInformation_hotelInformationRequest.setCid(1317094318479463123l);
        _getInformation_hotelInformationRequest.setCustomerIpAddress("CustomerIpAddress628231186");
        _getInformation_hotelInformationRequest.setCustomerSessionId("CustomerSessionId-2108019295");
        _getInformation_hotelInformationRequest.setCustomerUserAgent("CustomerUserAgent-1143777709");
        com.ean.wsapi.hotel.v3.LocaleType _getInformation_hotelInformationRequestLocale = com.ean.wsapi.hotel.v3.LocaleType.HR_HR;
        _getInformation_hotelInformationRequest.setLocale(_getInformation_hotelInformationRequestLocale);
        _getInformation_hotelInformationRequest.setCurrencyCode("CurrencyCode331226301");
        java.util.List<com.ean.wsapi.hotel.v3.MapEntry> _getInformation_hotelInformationRequestAdditionalData = new java.util.ArrayList<com.ean.wsapi.hotel.v3.MapEntry>();
        com.ean.wsapi.hotel.v3.MapEntry _getInformation_hotelInformationRequestAdditionalDataVal1 = new com.ean.wsapi.hotel.v3.MapEntry();
        _getInformation_hotelInformationRequestAdditionalDataVal1.setKey("Key1933407007");
        _getInformation_hotelInformationRequestAdditionalDataVal1.setValue("Value129523013");
        _getInformation_hotelInformationRequestAdditionalData.add(_getInformation_hotelInformationRequestAdditionalDataVal1);
        _getInformation_hotelInformationRequest.getAdditionalData().addAll(_getInformation_hotelInformationRequestAdditionalData);
        _getInformation_hotelInformationRequest.setSig("Sig1058173718");
        _getInformation_hotelInformationRequest.setDebug(Boolean.valueOf(false));
        _getInformation_hotelInformationRequest.setTest(Boolean.valueOf(true));
        _getInformation_hotelInformationRequest.setMinorRev(Integer.valueOf(-863234244));
        _getInformation_hotelInformationRequest.setHotelId(-7828349924918266974l);
        java.util.List<com.ean.wsapi.hotel.v3.HotelInfoOption> _getInformation_hotelInformationRequestOptions = new java.util.ArrayList<com.ean.wsapi.hotel.v3.HotelInfoOption>();
        com.ean.wsapi.hotel.v3.HotelInfoOption _getInformation_hotelInformationRequestOptionsVal1 = com.ean.wsapi.hotel.v3.HotelInfoOption.SUPPLIERS_CHAIN_CODE;
        _getInformation_hotelInformationRequestOptions.add(_getInformation_hotelInformationRequestOptionsVal1);
        _getInformation_hotelInformationRequest.getOptions().addAll(_getInformation_hotelInformationRequestOptions);
        com.ean.wsapi.hotel.v3.HotelInformationResponse _getInformation__return = port.getInformation(_getInformation_hotelInformationRequest);
        System.out.println("getInformation.result=" + _getInformation__return);


        }
        {
        System.out.println("Invoking getRateRules...");
        com.ean.wsapi.hotel.v3.HotelRateRulesRequest _getRateRules_hotelRateRulesRequest = new com.ean.wsapi.hotel.v3.HotelRateRulesRequest();
        _getRateRules_hotelRateRulesRequest.setApiKey("ApiKey-362673820");
        _getRateRules_hotelRateRulesRequest.setCid(-935925572151293830l);
        _getRateRules_hotelRateRulesRequest.setCustomerIpAddress("CustomerIpAddress55611087");
        _getRateRules_hotelRateRulesRequest.setCustomerSessionId("CustomerSessionId1958137672");
        _getRateRules_hotelRateRulesRequest.setCustomerUserAgent("CustomerUserAgent1010959451");
        com.ean.wsapi.hotel.v3.LocaleType _getRateRules_hotelRateRulesRequestLocale = com.ean.wsapi.hotel.v3.LocaleType.ET_EE;
        _getRateRules_hotelRateRulesRequest.setLocale(_getRateRules_hotelRateRulesRequestLocale);
        _getRateRules_hotelRateRulesRequest.setCurrencyCode("CurrencyCode175398957");
        java.util.List<com.ean.wsapi.hotel.v3.MapEntry> _getRateRules_hotelRateRulesRequestAdditionalData = new java.util.ArrayList<com.ean.wsapi.hotel.v3.MapEntry>();
        com.ean.wsapi.hotel.v3.MapEntry _getRateRules_hotelRateRulesRequestAdditionalDataVal1 = new com.ean.wsapi.hotel.v3.MapEntry();
        _getRateRules_hotelRateRulesRequestAdditionalDataVal1.setKey("Key1642642514");
        _getRateRules_hotelRateRulesRequestAdditionalDataVal1.setValue("Value-320976057");
        _getRateRules_hotelRateRulesRequestAdditionalData.add(_getRateRules_hotelRateRulesRequestAdditionalDataVal1);
        _getRateRules_hotelRateRulesRequest.getAdditionalData().addAll(_getRateRules_hotelRateRulesRequestAdditionalData);
        _getRateRules_hotelRateRulesRequest.setSig("Sig-1629116435");
        _getRateRules_hotelRateRulesRequest.setDebug(Boolean.valueOf(true));
        _getRateRules_hotelRateRulesRequest.setTest(Boolean.valueOf(false));
        _getRateRules_hotelRateRulesRequest.setMinorRev(Integer.valueOf(1953229004));
        _getRateRules_hotelRateRulesRequest.setHotelId(6106693171713324101l);
        _getRateRules_hotelRateRulesRequest.setArrivalDate("ArrivalDate1004882878");
        _getRateRules_hotelRateRulesRequest.setDepartureDate("DepartureDate-1005939602");
        com.ean.wsapi.hotel.v3.SupplierType _getRateRules_hotelRateRulesRequestSupplierType = com.ean.wsapi.hotel.v3.SupplierType.S;
        _getRateRules_hotelRateRulesRequest.setSupplierType(_getRateRules_hotelRateRulesRequestSupplierType);
        _getRateRules_hotelRateRulesRequest.setRoomTypeCode("RoomTypeCode-1847615242");
        _getRateRules_hotelRateRulesRequest.setRateCode("RateCode-1626714759");
        com.ean.wsapi.hotel.v3.RoomGroup _getRateRules_hotelRateRulesRequestRoomGroup = new com.ean.wsapi.hotel.v3.RoomGroup();
        java.util.List<com.ean.wsapi.hotel.v3.Room> _getRateRules_hotelRateRulesRequestRoomGroupRoom = new java.util.ArrayList<com.ean.wsapi.hotel.v3.Room>();
        com.ean.wsapi.hotel.v3.Room _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1 = new com.ean.wsapi.hotel.v3.Room();
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.setNumberOfAdults(443198665);
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.setNumberOfChildren(Integer.valueOf(230926921));
        java.util.List<java.lang.Integer> _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1ChildAges = new java.util.ArrayList<java.lang.Integer>();
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.getChildAges().addAll(_getRateRules_hotelRateRulesRequestRoomGroupRoomVal1ChildAges);
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.setFirstName("FirstName2100108218");
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.setLastName("LastName1319594456");
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.setBedTypeId("BedTypeId-778548795");
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.setBedTypeDescription("BedTypeDescription826244634");
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.setNumberOfBeds(Integer.valueOf(-178816401));
        com.ean.wsapi.hotel.v3.SmokingPreference _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1SmokingPreference = com.ean.wsapi.hotel.v3.SmokingPreference.NS;
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.setSmokingPreference(_getRateRules_hotelRateRulesRequestRoomGroupRoomVal1SmokingPreference);
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.setRoomTypeCode("RoomTypeCode-1305952760");
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.setRateCode("RateCode573989344");
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.setRateKey("RateKey-1663851551");
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.setRoomDescription("RoomDescription-31772203");
        _getRateRules_hotelRateRulesRequestRoomGroupRoomVal1.setChargeableRate(Float.valueOf(0.5321385f));
        _getRateRules_hotelRateRulesRequestRoomGroupRoom.add(_getRateRules_hotelRateRulesRequestRoomGroupRoomVal1);
        _getRateRules_hotelRateRulesRequestRoomGroup.getRoom().addAll(_getRateRules_hotelRateRulesRequestRoomGroupRoom);
        _getRateRules_hotelRateRulesRequest.setRoomGroup(_getRateRules_hotelRateRulesRequestRoomGroup);
        com.ean.wsapi.hotel.v3.HotelRateRulesResponse _getRateRules__return = port.getRateRules(_getRateRules_hotelRateRulesRequest);
        System.out.println("getRateRules.result=" + _getRateRules__return);


        }

        System.exit(0);
    }

}
